major version checking refactoring of scripts

diff --git a/scripts/bak b/scripts/bak
--- a/scripts/bak
+++ b/scripts/bak
@@ -1,6 +1,20 @@
 #!/usr/bin/env bash
-# bak 1.1.0
+# bak 1.1.1
 # Backs up given file or directory
+
+set -euo pipefail  # Fail on any error
+Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
+
+check_version() {
+    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
+    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
+    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
+        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
+        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
+    fi
+}
+
+check_version
 
 if [[ ! -d "$1" && ! -f "$1" ]]; then
     printf "Usage: `basename $0` <File|Directory>\n"
diff --git a/scripts/build_go b/scripts/build_go
--- a/scripts/build_go
+++ b/scripts/build_go
@@ -2,15 +2,15 @@
 # build_go 1.2.1
 # Generic script to compile Go programs
 
-set -euo pipefail  # Fail immediately on any error
+set -euo pipefail  # Fail on any error
 Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
 
 check_version() {
     LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
     LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
     if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
-        printf "${Yel}==> Warning: Running older ${Rst}${Mag}v${LocalVer}${Rst} ${Yel}version of \
-        this script. Run with '-u' argument to upgrade to latest${Rst} ${Mag}v${LatestVer}${Rst}\n"
+        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
+        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
     fi
 }
 
diff --git a/scripts/certls b/scripts/certls
--- a/scripts/certls
+++ b/scripts/certls
@@ -1,9 +1,20 @@
 #!/usr/bin/env bash
-# certls 1.1.0
+# certls 1.1.1
 # Given an FQDN show all assigned SSL certificates 
 
-set -euo pipefail  # Fail immediately if any errors
-Blu='\x1b[1;34m' Gre='\x1b[32m' Red='\x1b[31m' Yel='\x1b[1;33m' Rst='\x1b[0m'
+set -euo pipefail  # Fail on any error
+Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
+
+check_version() {
+    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
+    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
+    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
+        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
+        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
+    fi
+}
+
+check_version
 
 if [[ -z "$(which openssl)" ]]; then
     printf "Missing 'openssl' binary\n"
diff --git a/scripts/dl b/scripts/dl
--- a/scripts/dl
+++ b/scripts/dl
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# dl 1.1.0
+# dl 1.1.1
 # A simple yt-dlp, the famous video downloader, stub driver
 
 # Install yt-dl:
@@ -9,7 +9,21 @@
 #   Upgrade yt-dl:
 #     yt-dlp --update-to nightly
 #     yt-dlp --version
-#   
+#
+
+set -euo pipefail  # Fail on any error
+Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
+
+check_version() {
+    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
+    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
+    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
+        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
+        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
+    fi
+}
+
+check_version
 
 if [[ "$#" -ne 2 ]]; then
     printf "Usage: $0 FILENAME \"URL\"\n"
diff --git a/scripts/git_remotev b/scripts/git_remotev
--- a/scripts/git_remotev
+++ b/scripts/git_remotev
@@ -1,8 +1,18 @@
 #!/usr/bin/env bash
-# git_remotev 1.1.1
+# git_remotev 1.1.2
 # List remote sources of all git repos
 
-set -euo pipefail
+set -euo pipefail  # Fail immediately on any error
+Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
+
+check_version() {
+    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
+    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" | sed -n '2p' | awk '{print $NF}')
+    [[ "$LocalVer" < "$LatestVer" ]] && printf "${Yel}==> Warning: Running older ${Rst}${Mag}v${LocalVer}${Rst} ${Yel}version of this script. Run with '-u' argument to upgrade to latest${Rst} ${Mag}v${LatestVer}${Rst}\n"
+}
+
+check_version
+
 for r in `ls -d */` ; do
     r=${r%?}
     if [[ -d "$r/.git" ]]; then
