major version checking refactoring of scripts

diff --git a/scripts/pman b/scripts/pman
--- a/scripts/pman
+++ b/scripts/pman
@@ -1,10 +1,23 @@
 #!/usr/bin/env bash
-# pman 1.2.0
+# pman 1.3.0
 # Azure REST API caller
+
+set -euo pipefail  # Fail on any error
+Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
+
+check_version() {
+    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
+    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
+    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
+        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
+        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
+    fi
+}
+
+check_version
 
 PrgName="pman"
 PrgVer="1.1.1"
-set -euo pipefail
 
 check_binary() {
     if [[ -z "$(which $1 2>/dev/null)" ]]; then
diff --git a/scripts/webm2mp4 b/scripts/webm2mp4
--- a/scripts/webm2mp4
+++ b/scripts/webm2mp4
@@ -1,9 +1,21 @@
 #!/usr/bin/env bash
-# webm2mp4 1.1.0
+# webm2mp4 1.2.0
 # Converts WEBM format files to MP4 format
 
-set -euo pipefail
-Gre='\e[1;32m' Red='\e[1;31m' Pur='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
+set -euo pipefail  # Fail on any error
+Gre='\e[1;32m' Red='\e[1;31m' Mag='\e[1;35m' Yel='\e[1;33m' Blu='\e[1;34m' Rst='\e[0m'
+
+check_version() {
+    LocalVer=$(sed -n '2p' "$0" | awk '{print $NF}')
+    LatestVer=$(curl -ks "https://que.one/scripts/$(basename $0)" 2>/dev/null | sed -n '2p' | awk '{print $NF}')
+    if [[ -n "$LatestVer" && "$LocalVer" < "$LatestVer" ]]; then
+        printf "${Yel}==> Warning: Running older ${Rst}${Red}v${LocalVer}${Rst} ${Yel}version "
+        printf "of this script. Please update to latest${Rst} ${Gre}v${LatestVer}${Rst}\n"
+    fi
+}
+
+check_version
+
 Utility="$(basename $0)" # This script filename
 if [[ -z "${1:-}" ]]; then
     printf "Usage: %b%s%b FILENAME\n" "${Yel}" "${Utility}" "${Rst}"
